TARGETS=primetest dump_recordlog
TESTS=
EXTRA_DEPS=$(BASEDIR)/lib/libopeninstrument.a
EXTRA_LIBS_dump_recordlog := $(BASEDIR)/server/record_log.o

include $(BASEDIR)/Makefile.inc

dump_recordlog: dump_recordlog.o

## DEPENDENCIES START HERE (do not remove this line)
